### ISSUE TITLE
TypeError: Cannot read property 'hide' of undefined

### ISSUE THREAD

**Issue by allanmviana** [uenify/google-tasks-desktop#1]
So, this is happening with me when I try launch the app:

```C:\Users\Allan Viana\Desktop\google-tasks-desktop-master>npm start
> google-tasks-desktop@1.0.0 start C:\Users\Allan Viana\Desktop\google-tasks-desktop-master
> electron-forge start

√ Checking your system
√ Locating Application
√ Preparing native dependencies
√ Launching Application

 App threw an error during load
TypeError: Cannot read property 'hide' of undefined
    at Object.<anonymous> (C:\Users\Allan Viana\Desktop\google-tasks-desktop-master\src\index.js:17:20)
    at Object.<anonymous> (C:\Users\Allan Viana\Desktop\google-tasks-desktop-master\src\index.js:367:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Allan Viana\Desktop\google-tasks-desktop-master\node_modules\electron-compile\lib\require-hook.js:77:14)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at init (C:\Users\Allan Viana\Desktop\google-tasks-desktop-master\node_modules\electron-compile\lib\config-parser.js:294:16)
    at main (C:\Users\Allan Viana\Desktop\google-tasks-desktop-master\node_modules\electron-prebuilt-compile\lib\es6-init.js:58:29)

```
Windows 10

**Comment by allanmviana** [comment]
Now I get it. The code is only working on MacOS. So running in Windows are a lot of functions errors.

**Comment by allanmviana** [comment]
Ok, you may close this issue if want.
I resolved by adjusting the whole code to my computer. You can see the [my index.js here](https://github.com/allanmviana/google-tasks-desktop/blob/master/src/index.js).

The main changes were:
- function .hide not working on my PC (maybe all windows 10 are like that)
- skipTaskbar also not workin. So I just comented that part of code (l. 17, my original problem)
- Lines 35 and 37: getting the bounds was not working, just sending the window so far I couldn't even see in monitor.
- Logos changed to white.
- BrowserWindow set to my own configuration.

And thats it. 
Thank you very much for the script!
